# Generated by Django 4.1.6 on 2023-02-16 15:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BrngPres',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('barangay', models.CharField(max_length=255)),
                ('contact_number', models.CharField(max_length=11)),
            ],
        ),
    ]
