# Generated by Django 4.1.6 on 2023-02-19 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parnt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='mid_name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
