# Generated by Django 4.1.6 on 2023-02-19 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parnt', '0002_alter_parent_mid_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='other_incom_src',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
