# Generated by Django 4.1.6 on 2023-02-16 21:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('schedule', models.DateTimeField()),
                ('description', models.CharField(max_length=255)),
                ('message', models.TextField()),
            ],
        ),
    ]
